### ISSUE TITLE
[0.9.8] no way to define "do not archive"?

### ISSUE THREAD

**Issue by RalfWW** [Brummolix/AutoarchiveReloaded#10]
I'm trying to define a rule for
"Du not sync -Nachrichten mit Schlagwörtern-" by setting 

"Archiviere Nachrichten mit Schlagwörtern älter als 0 Tage"

This archives all Messages with "Schlagwörtern" :-/

A setting of "-1" would be appreciate to handle the goal.

Any other way to get this?

Ralf

**Comment by Brummolix** [comment]
Just uncheck the box before "Archiviere Nachrichten mit Schlagwörtern älter als"
> all messages with tags will remain

**Comment by RalfWW** [comment]
Thanks!

Am 14.04.2015 um 19:13 schrieb Brummolix:
