### ISSUE TITLE
How to achive sent folders

### ISSUE THREAD

**Issue by Steve499** [Brummolix/AutoarchiveReloaded#11]
Have loaded the addon to replace the older 'AutoArchive' which worked well but only archived the Inbox.
How do you set up Thunderbird/AutoarchiveReloaded to archive sent folder as well?

**Comment by Brummolix** [comment]
Have you read the manual here?
http://brummolix.github.io/AutoarchiveReloaded/

All folders of an account are archived if you have set up the account itself.
(except some special folders like Draft,Trash,Templates,Junk,Archive,Queue)
