### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by cpuch** [Brummolix/AutoarchiveReloaded#13]
Hello,

Your extension is really useful. I'd like to translate it in french. How can I do that?
Thank you

**Comment by Brummolix** [comment]
Hi

thank you for contribution.

if you like to translate it, please have a look at https://github.com/Brummolix/AutoarchiveReloaded/tree/master/chrome/locale/de-DE
Translate the content in all 3 files.

Also have a look at https://github.com/Brummolix/AutoarchiveReloaded/blob/master/install.rdf
The section under <em:localized> must be translated. And give me the name I shall add under <em:contributor>

Please attach all the files here.
Then I can build a french version.
(If you are familar with GitHub you could also fork the repository and send me a pull request with all changes, but it is very OK to simply attach the files here).

**Comment by Brummolix** [comment]
Maybe it was a stupid idea to point you to the german files.
Off course you can also use the english ones:
https://github.com/Brummolix/AutoarchiveReloaded/tree/master/chrome/locale/en-US

**Comment by cpuchalver** [comment]
Hello,

I send you a pull request as Github won't let met attach files here.

Thank you

**Comment by Brummolix** [comment]
I have merged the pull request and now created a beta version with french language.
Please check, see https://github.com/Brummolix/AutoarchiveReloaded/releases/tag/0.9.9_beta

In my eyes it is looking good but I don't understand french :)
At least I saw 2 places where it could be good to have shorter texts.
See attachments.
![button](https://cloud.githubusercontent.com/assets/6218021/10467394/bddcd222-71f9-11e5-8569-cd72ecac51c2.PNG)
![properties](https://cloud.githubusercontent.com/assets/6218021/10467496/5df0c1e2-71fa-11e5-8f3e-d8de25e3dc18.png)

**Comment by cpuchalver** [comment]
I just checked the beta version and it looks good. As for the shorter texts, unfortunately it is as it should be translated. Maybe the button could simply say "Archivage auto" and in the account settings, it could be shorten to "Paramètres d'archivage auto".

**Comment by Brummolix** [comment]
I have shortened the properties message.
For the button I was wrong, the "..." is part of the message, so everything is right there.

I have now released version 0.9.9 to Mozilla (but it will probably take some time until Mozilla have validated it).

Finally we are almost finished, but as (hopefully) last part I would need the french description for the Mozilla webpage:
See https://addons.mozilla.org/fr/thunderbird/addon/autoarchivereloaded/
Please translate the "À propos de ce module" part and post it here.

Thank you.

**Comment by Brummolix** [comment]
Ahhh, this was german again.
See here: https://addons.mozilla.org/en-us/thunderbird/addon/autoarchivereloaded/
Also do not forget the main description "Automatically archives old mails (Improved version of the orginal Autoarchive Add-on)"

**Comment by cpuchalver** [comment]
Here is the translation for the short description:

*Archive automatiquement les anciens mails (version améliorée de l'extension Autoarchive)*

And the "about this add-on" translation:

*A propos de cette extension
Thunderbird peut archiver les messages mais vous devez le faire manuellement pour chaque message.
Cette extension vous permet d'archiver automatiquement vos mails après une certaine période.
Vous pouvez par exemple l'utiliser pour archiver les messages de votre compte IMAP (ou généralement l'espace est restreint) vers vos dossiers locaux.*

*Voir les instructions : http://brummolix.github.io/AutoarchiveReloaded/
Rapporter un bug : https://github.com/Brummolix/AutoarchiveReloaded/issues*

*Attention
Vous utilisez l'extension à vos risques et périls. Certains utilisateurs (peu) ont reporté avoir perdu des données.*

*Cette extension est une version améliorée de l'extension appelée "Autoarchive".*
*Améliorations:*
- *Archivage du Courrier entrant mais aussi d'autres dossiers comme Messages envoyés (Spam, Corbeille, Brouillons, Modèles, Boîte d'envoi et Archives seront toujours ignorés)*
- *Gestion des sous-dossiers*
- *Configuration des messages non-lus séparément (en plus de messages suivis et des messages avec des mots clés)*
- *Amélioration du traitement si un message est par exemple suivi et a des mots-clés*
- *Affichage de l'activité dans une fenêtre*
- *Archivage via le menu / la barre d'outils*
- *Choix du lancement de l'archivage automatique à chaque démarrage de Thunderbird ou manuellement*
- *Ajout de possibilité (limitées) pour archiver les comptes RSS (limitées car Thunderbird ne possède pas d'options pour archiver les comptes de flux, vous ne pouvez donc utiliser que les paramètres par défaut)*

**Comment by Brummolix** [comment]
Thank you.
This is now included at the Mozilla page.
The new version is meanwhile also accepted by Mozilla and available to the public.

**Comment by Brummolix** [comment]
Can you translate the following texts for the next version?

General
Logging
Save settings
Settings saved.
specific settings for account $$TITLE$$

**Comment by cpuch** [comment]
I create a pull request
