### ISSUE TITLE
"this.view.dbView is null" with TorBirdy

### ISSUE THREAD

**Issue by Brummolix** [Brummolix/AutoarchiveReloaded#19]
I splitted this issue out of #18 from tomreyn:

If I then start TB again using my default locale (i.e. without the LANG=C), AutoArchive Reloaded again shows up as "null" on the extension list. However, it now shows with a properly localized description text, and I can access its (properly localized) preferences menu as well.

Trying to do an auto-archiving run results in this message written to error log, though:

`12.9.2016, 21:58:42 - AutoarchiveReloaded - ERROR: TypeError: this.view.dbView is null; Source: 'chrome://messenger/content/folderDisplay.js'; Line: 1449; code: (new TypeError("this.view.dbView is null", "chrome://messenger/content/folderDisplay.js", 1449)); stack: FolderDisplayWidget_hintAboutToDeleteMessages@chrome://messenger/content/folderDisplay.js:1449:5
FolderDisplayWidget_hintMassMoveStarting@chrome://messenger/content/folderDisplay.js:1465:5
BatchMessageMover.prototype.archiveMessages@chrome://messenger/content/mailWindowOverlay.js:1628:5
AutoarchiveReloadedOverlay.SearchListener.prototype.archiveMessages@chrome://autoarchivereloaded/content/overlay.js:304:9
AutoarchiveReloadedOverlay.SearchListener.prototype.onSearchDone@chrome://autoarchivereloaded/content/overlay.js:386:18
`

Update: On a repeat run (with the extensions' own logging to file enabled), auto-archiving actually works.

**Comment by Brummolix** [comment]
The error is probably the same as #1, #5 and #7

**Comment by Brummolix** [comment]
I could reproduce the following:
If no folder is selected, something has to be archived and TorBirdy was installed >> "this.view.dbView is null" error.
If a folder is selected it worked with and without TorBirdy.
If no folder is selected and TorBirdy was not installed it worked, too (AutoArchive selects the folder itself)

I could not reproduce any change if extended logging is on or off.

I have now created another beta version, can you please try this one if you see the "this.view.dbView is null" error again?
https://github.com/Brummolix/AutoarchiveReloaded/releases/download/0.9.9.3_beta_2/AutoarchiveReloaded_0.9.9.3_beta_2.xpi

**Comment by tomreyn** [comment]
Using 0.9.9.3 beta *1* (not 2), with TorBirdy installed, and no folder selected, I am (and was) unable to reproduce the "this.view.dbView is null" error (the report quoted above refers to version 0.9.9.2). Do you want me to test beta *2* nevertheless?

**Comment by Brummolix** [comment]
That's strange (like everything arround this bug)...
It would be nice if you could do a quick test with beta 2 nevertheless.
If this is succesful I will release the version.

**Comment by tomreyn** [comment]
Tested:

1. Uninstalled AAR 0.9.9.3 beta1
2. Restarted TB
3. Tried to install AAR 0.9.9.2 from AMO (using the TB add-on search): FAILED - listing AAR as 'null' in list of installed add-ons; after TB restart all visible traces of this add-on are gone
4. Restarted TB
5. Tried to install AAR 0.9.9.2 using 'install add-on from file' GUI option and AAR downloaded from AMO: FAILED - nothing happens on GUI, installation prompt does not show up, promise chain failure error logged on console. XPI sha1sum 8025a58da47b62836ffe798aaf24cd74749a0e2c, sha256sum 8683e30c53b329022f918e8172245e546ee7b97b2f1909dd1b337ef23d170c4c
6. Restarted TB
7. Tried to install AAR 0.9.9.3 beta2 using 'install add-on from file' GUI option and AAR downloaded from AMO: SUCCESS - installation prompt shows up, once confirmed, add-on is properly listed as installed, pending restart, no errors on console.
8. Restarted TB
9. Verified AAR is properly installed (listed on installed add-ons, global preferences are available and localized).
10. Did a test archiving run - nothing is logged or reported on either screen or console. _Seems_ to have worked.

**Comment by Brummolix** [comment]
Thanks.

Released via 0.9.9.3 (may take some time until it is reviewed and accepted by Mozilla).
