### ISSUE TITLE
Cant install Addon because it was damaged

### ISSUE THREAD

**Issue by Tealk** [Brummolix/AutoarchiveReloaded#22]
Hallo,

i cant install this addon. Thunderburd say me it should be damaged.
![image](https://user-images.githubusercontent.com/12276250/38136709-9c5d3f56-3420-11e8-8e15-f1478f036265.png)

**Comment by Brummolix** [comment]
I just tried with the download from https://addons.mozilla.org/de/thunderbird/addon/autoarchivereloaded/ and can install it.

Maybe your downloaded file is corrupted?
Please redownload it.

**Comment by Tealk** [comment]
I have downlaod it 3 times with 2 different browsers

**Comment by Brummolix** [comment]
Which version of Thunderbird did you use?
Is it the beta version?
I see, in TB60 it does not workl

**Comment by Tealk** [comment]
yes i use tb 60b1

**Comment by Brummolix** [comment]
I created a new version that should be compatible with TB 60. You can download it at Mozilla.

**Comment by Brummolix** [comment]
Does the new version work?

**Comment by Tealk** [comment]
yes it looks like so, thank you :)

**Comment by Tealk** [comment]
yes it looks like so, thank you
