### ISSUE TITLE
"All Mail" issue with March 31 update

### ISSUE THREAD

**Issue by mkelleycprw** [Brummolix/AutoarchiveReloaded#23]
Hi. Since your March 31 update, AutoArchive has forced an "All Mail" folder for my accounts to appear in the archive folder list that significantly slows Thunderbird. This folder exists even when I've specified an "Archives" folder for the account.

Thanks,
Melissa Kelley CPRW

**Comment by Brummolix** [comment]
Are you sure that this changed behavior is coming from the Addon update?
There was no change regarding the folders. It is even true, that the Addon is not creating any folder. Instead it simply tells Thunderbird to archive messages with whatever archive settings are set.

Did you also update Thunderbird at the same time or changed any other settings?
What happens when you select multiple messages in Thunderbird and then press "Archive" in the context menu (right mouse click)? Does it use the same folders as the Addon or others?

**Comment by mkelleycprw** [comment]
Thanks for the reply!
    
    I looked further into the issue and realized that I was subscribed
    to "All Mail" folders in my IMAP settings. I've unsubscribed and the
    problem seems to be resolved.
    
    Melissa Kelley CPRW 
      
      Founder | Executive Resume Writer
          Kelley Resumes & Wordsmithing
         http://kelres.weebly.com
      
      720-588-9793
          LinkedIn: www.linkedin.com/in/mkelleycprw
    On 4/16/2018 1:29 PM, Brummolix wrote:
    
    
      Are you sure that this changed behavior is coming from the
        Addon update?
        There was no change regarding the folders. It is even true, that
        the Addon is not creating any folder. Instead it simply tells
        Thunderbird to archive messages with whatever archive settings
        are set.
      Did you also update Thunderbird at the same time or changed any
        other settings?
        What happens when you select multiple messages in Thunderbird
        and then press "Archive" in the context menu (right mouse
        click)? Does it use the same folders as the Addon or others?
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Brummolix/AutoarchiveReloaded","title":"Brummolix/AutoarchiveReloaded","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Brummolix/AutoarchiveReloaded"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Brummolix in #23: Are you sure that this changed behavior is coming from the Addon update?\r\nThere was no change regarding the folders. It is even true, that the Addon is not creating any folder. Instead it simply tells Thunderbird to archive messages with whatever archive settings are set.\r\n\r\nDid you also update Thunderbird at the same time or changed any other settings?\r\nWhat happens when you select multiple messages in Thunderbird and then press \"Archive\" in the context menu (right mouse click)? Does it use the same folders as the Addon or others?"}],"action":{"name":"View Issue","url":"https://github.com/Brummolix/AutoarchiveReloaded/issues/23#issuecomment-381721437"}}}
