### ISSUE TITLE
Archive now button does nothing

### ISSUE THREAD

**Issue by rstaylor** [Brummolix/AutoarchiveReloaded#29]
I have configured AutoarchiveReloaded on my Thunderbird install.  I have configured the account settings in both Copies & Folders and in the AutoArchive settings.  All boxes are checked and are setup for either 270 or 360 days.  I also flagged this to run the archiving on startup.  This does nothing as does clicking 'ArchiveNow' on the Tools menu.  below is the log from startup and a manual attempt at archiving.Fro some reason my email account is being ignored.

16/01/2019, 16:53:07 - AutoarchiveReloaded - INFO: start...
16/01/2019, 16:53:07 - AutoarchiveReloaded - INFO: ApplicationInfo ID:{3550f703-e582-4d05-9a08-453d09bdfdc6}; Version:60.2.1; BuildID:20181010142617; PlatformVersion:60.2.1; PlatformBuildID:20181010142617; language: en-GB
16/01/2019, 16:53:07 - AutoarchiveReloaded - INFO: SystemInfo Linux x86_64| Linux x86_64| Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Thunderbird/60.2.1
16/01/2019, 16:53:07 - AutoarchiveReloaded - INFO: Account Info: 'Local Folders'; type: none; localStoreType: mailbox; mailbox://nobody@Local%20Folders
16/01/2019, 16:53:07 - AutoarchiveReloaded - INFO: Account Info: 'xxxx on owa.xxxx.com'; type: exquilla; localStoreType: exquilla; exquilla://xxxx%40xxxx%2Ecom@owa.xxxx.com
16/01/2019, 16:53:09 - AutoarchiveReloaded - INFO: ready for work
16/01/2019, 16:53:09 - AutoarchiveReloaded - INFO: archive type manually
16/01/2019, 16:53:09 - AutoarchiveReloaded - INFO: Installed Addon-Info: Messaging Menu and Unity Launcher integration (messagingmenu@mozilla.com) version 1.4; active: true
16/01/2019, 16:53:09 - AutoarchiveReloaded - INFO: Installed Addon-Info: Default ({972ce4c6-7e08-4474-a285-3208198ce6fd}) version 60.2.1; active: true
16/01/2019, 16:53:09 - AutoarchiveReloaded - INFO: Installed Addon-Info: English (GB) Language Pack (langpack-en-GB@thunderbird.mozilla.org) version 60.0; active: true
16/01/2019, 16:53:09 - AutoarchiveReloaded - INFO: Installed Addon-Info: Lightning Calendar Tabs (lightningcalendartabs@jlx.84) version 2.2; active: true
16/01/2019, 16:53:09 - AutoarchiveReloaded - INFO: Installed Addon-Info: ExQuilla for Microsoft Exchange (exquilla@mesquilla.com) version 60.0; active: true
16/01/2019, 16:53:09 - AutoarchiveReloaded - INFO: Installed Addon-Info: Lightning ({e2fda1a4-762b-4020-b5ad-a41df1933103}) version 6.2.2.1; active: true
16/01/2019, 16:53:09 - AutoarchiveReloaded - INFO: Installed Addon-Info: TbSync (tbsync@jobisoft.de) version 0.7.22; active: true
16/01/2019, 16:53:09 - AutoarchiveReloaded - INFO: Installed Addon-Info: Provider for Exchange ActiveSync (eas4tbsync@jobisoft.de) version 0.9; active: true
16/01/2019, 16:53:09 - AutoarchiveReloaded - INFO: Installed Addon-Info: Signature Switch ({2ab1b709-ba03-4361-abf9-c50b964ff75d}) version 1.7.1; active: true
16/01/2019, 16:53:09 - AutoarchiveReloaded - INFO: Installed Addon-Info: Provider for CalDAV & CardDAV (dav4tbsync@jobisoft.de) version 0.10; active: true
16/01/2019, 16:53:09 - AutoarchiveReloaded - INFO: Installed Addon-Info: AutoarchiveReloaded (AutoarchiveReloaded@brummolix.addons.mozilla.org) version 0.9.9.6; active: true
16/01/2019, 16:53:09 - AutoarchiveReloaded - INFO: Installed Addon-Info: Light (thunderbird-compact-light@mozilla.org@personas.mozilla.org) version ; active: false
16/01/2019, 16:53:09 - AutoarchiveReloaded - INFO: Installed Addon-Info: Dark (thunderbird-compact-dark@mozilla.org@personas.mozilla.org) version ; active: false
16/01/2019, 16:59:35 - AutoarchiveReloaded - INFO: try manual archive
16/01/2019, 16:59:37 - AutoarchiveReloaded - INFO: start archiving
16/01/2019, 16:59:37 - AutoarchiveReloaded - INFO: check account 'Local Folders'
16/01/2019, 16:59:37 - AutoarchiveReloaded - INFO: Settings for 'Local Folders':
16/01/2019, 16:59:37 - AutoarchiveReloaded - INFO: - archive other false
16/01/2019, 16:59:37 - AutoarchiveReloaded - INFO: - days other 0
16/01/2019, 16:59:37 - AutoarchiveReloaded - INFO: - archive marked false
16/01/2019, 16:59:37 - AutoarchiveReloaded - INFO: - days marked 0
16/01/2019, 16:59:37 - AutoarchiveReloaded - INFO: - archive tagged false
16/01/2019, 16:59:37 - AutoarchiveReloaded - INFO: - days tagged 0
16/01/2019, 16:59:37 - AutoarchiveReloaded - INFO: - archive unread false
16/01/2019, 16:59:37 - AutoarchiveReloaded - INFO: - days unread 0
16/01/2019, 16:59:37 - AutoarchiveReloaded - INFO: autoarchive disabled, ignore account 'Local Folders'
16/01/2019, 16:59:37 - AutoarchiveReloaded - INFO: check account 'xxxx on owa.xxxx.com'
16/01/2019, 16:59:37 - AutoarchiveReloaded - INFO: ignore account 'xxxx on owa.xxxx.com'
16/01/2019, 16:59:37 - AutoarchiveReloaded - INFO: archive (searching messages to archive) done

**Comment by Brummolix** [comment]
According to the log your account is of type "exquilla" so its an Exchange account.
Right now this type is unknown to Autoarchive Reloaded and therefore ignored.

I can enable it but I have no possibility to test it.
Would you like to test it? It might be a good idea to create some backup before.

**Comment by Brummolix** [comment]
You can try the beta version
https://github.com/Brummolix/AutoarchiveReloaded/releases/download/0.9.9.6.2_beta/AutoarchiveReloaded_0.9.9.6.2_beta.xpi

**Comment by rstaylor** [comment]
I can try it.  Getting a back will be difficult, but I can do this with no internet connection to be sure that it does not wipe out my whole email system.  If it does I can just blow away the account before connecting back the internet.  I will then reconfigure the account and recover the data from the exchange server.

Sound like a workable plan to you?


Richard S Taylor

Sales Engineer
InterSystems Corporation
Office: 443-340-8614
FAX: 440-815-5805
[636c6970626f6172642e706e67]


On 1/17/19 5:32 PM, Brummolix wrote:

According to the log your account is of type "exquilla" so its an Exchange account.
Right now this type is unknown to Autoarchive Reloaded and therefore ignored.

I can enable it but I have no possibility to test it.
Would you like to test it? It might be a good idea to create some backup before.

**Comment by Brummolix** [comment]
Does it work?

**Comment by rstaylor** [comment]
Sorry, I have not had the chance.  I will try to do this within the next week.


Richard S Taylor

Sales Engineer
InterSystems Corporation
Office: 443-340-8614
FAX: 440-815-5805
[636c6970626f6172642e706e67]


On 1/22/19 5:20 PM, Brummolix wrote:

Does it work?

**Comment by rstaylor** [comment]
I wanted to let you know that I finally had a chance to install the beta version you sent the link for .  This appears to have worked great.  I like the fact that it automatically puts things under folders by year.  I had a moment where I was worried because I didn't see an Inbox folder then I realized that this was kept under the year folder directly.


Richard S Taylor

Sales Engineer
InterSystems Corporation
Office: 443-340-8614
FAX: 440-815-5805
[636c6970626f6172642e706e67]


On 1/22/19 5:20 PM, Brummolix wrote:

Does it work?

**Comment by Brummolix** [comment]
The year folders are a setting of Thunderbird. You can set it up under:
- right click at an account
- choose "Properties"
- choose "Copies and folders"
- press the "archive settings..."
