### ISSUE TITLE
Needs to be able to be upgraded for Thunderbird 68.0

### ISSUE THREAD

**Issue by andrey-helldar** [Brummolix/AutoarchiveReloaded#32]
The extension does not work in Thunderbird 68.
![2019-09-20_13-08-03](https://user-images.githubusercontent.com/10347617/65319176-b4bfc980-dba7-11e9-9fcc-2ce27dc4aa78.png)

**Comment by Brummolix** [comment]
You can use the new release from https://github.com/Brummolix/AutoarchiveReloaded/releases/tag/1.0.0.0
At the moment I am not able to upload the release to Mozilla, see https://thunderbird.topicbox.com/groups/addons/T409cd22eca2f3864/cant-upload-addon-on-addons-thunderbird-net

**Comment by tooomm** [comment]
Thanks for taking care already - that was quick!

But maybe you want to keep this open for others to find more easily until it's available at Mozilla? Who knows how long it'll take...

**Comment by Brummolix** [comment]
I put a not at https://addons.thunderbird.net/de/thunderbird/addon/autoarchivereloaded/
