### ISSUE TITLE
No settings menu with tb 78.6

### ISSUE THREAD

**Issue by fanf** [Brummolix/AutoarchiveReloaded#56]
I've installed autoarchive on thunderbird 78.6. 

Installation seems OK:
- in the `add-ons manager` tab, I see the plugin, 
- in the main toolbar, I have a button "autoarchive..." and if I click on it, I can see a warning message about imap and can click OK

BUT: I don't have access to the settings menu anywhere. I looked in the humburger button next to autoarchive one in bar, nothing. Nothing in tools menu; nothing anywhere I thought about (see screens).

Also: when I click on the "autoarchive" button, I get an error in the console log: "browser is null".

I tried to reinstall plugin. 
Is it some incompatibility problem? Thanks for any help. 

![image](https://user-images.githubusercontent.com/44649/104005056-dbdb4980-51a4-11eb-9920-4b0e5f0e1824.png)

![image](https://user-images.githubusercontent.com/44649/104005098-e695de80-51a4-11eb-9662-04a85be4e5c4.png)
 
![image](https://user-images.githubusercontent.com/44649/104005298-2eb50100-51a5-11eb-8f97-a5422e60a7fe.png)

**Comment by Brummolix** [comment]
I just installed the addon in TB 78.6 in Windows and indeed the settings were missing.
The addon options menu seem to be not available at all in this Thunderbird version (german version in windows).
Neverthelesse then you should be able to find the addon settings in the view of the installed addon under the menu with the 3 dots. (see image)
![grafik](https://user-images.githubusercontent.com/6218021/104091438-a35b6e80-527d-11eb-8239-0331cefe4133.png)

But after installation the settings did not show up there.
What helped on my machine was to disable the addon (the blue button in the image) and to enable it again. Then the settings were available.
Please try if this helps.

**Comment by Brummolix** [comment]
This seem to be a bug in Thunderbird as the addon does not control this settings stuff, instead it only registers its settings page and all the UI is done by thunderbird.

**Comment by fanf** [comment]
@Brummolix: you're right, disable/enable again the plugin and the preference appeared. Weird. Thanks for the tip, I wouldn't ever have found if.

**Comment by fanf** [comment]
I believe that issue can be closed, since it's not a bug with the plugin by itself.
