### ISSUE TITLE
Archiving does not start but produces error shown in error console

### ISSUE THREAD

**Issue by pooka27** [Brummolix/AutoarchiveReloaded#57]
Hi,
When clicking the AutoArchive Button archiving process does not start but shows an error in the error console (after enabling logging in the options):
Error: Could not establish connection. Receiving end does not exist. popup.js:143:44
    initialize moz-extension://5fb95b5a-5aee-4536-995a-3e77be8051f6/popup.js:143
Please advise.
Add on was working before but stopped workingproperly.
OS is Kubuntu 18.04 64 Bit, Thunderbird is 68.10.0 (64-bit), AutoArchiveReloaded is 1.0.0.4 from August 21 2020
Best regards
Andreas

**Comment by Brummolix** [comment]
Did you try to uninstall and reinstall the addon?

**Comment by pooka27** [comment]
Re-installing the addon solved the issue.
Thanks for the quick reply!
