### ISSUE TITLE
AutoarchiveReloaded doesn't work with TB 91

### ISSUE THREAD

**Issue by slayerjk** [Brummolix/AutoarchiveReloaded#71]
Hello.

After updating TB from 78x to 91x(91.5.0) AutoarchiveReloaded has stopped to work.
It doesn't autoarchive at start.
It doesn't archive by pressing toolbar button.

I've tried to reinstall it - same result.

Is your app is uncompatible with TB 90x ?

**Comment by Brummolix** [comment]
Autoarchive Reloaded should work with TB 91.
Which version of Autoarchive Reloaded is installed? The latest version should be 1.0.0.5.
Do you use it on Windows or a different OS?

Please activate the extended logging in the setting. After that please try to archive again.
Then open the error console (STRG + SHIFT + J / or at the menu Extras\developer tools\error console)
There you should now see log messages from Autoarchive Reloaded (and others as well).
Do you see any errors there?
Can you attach these logs? (You might check them before posting, as they may contain personal data).

**Comment by slayerjk** [comment]
AutoarchiveReloaded is 1.0.0.5.
I use Windows OS.

I've activated additional logging.
Opened console, started Autoarchive.
No errors in console.
Due to confidential(Work account) I can't attach this log.

But what I see ...

Big pardon really, it work fine, just misunderstanding due to new year cycle.

**Comment by slayerjk** [comment]
No issue, misunderstood retention date.
Sorry to disturb.
