### ISSUE TITLE
Thunderbird Crash since v102.3.0

### ISSUE THREAD

**Issue by Nono-m0le** [Brummolix/AutoarchiveReloaded#79]
When I'm clicking on the AutoArchive button, TB completely crash (and try to open crashreporter.exe).
This seems quite recent but I can't figure out where to check for log/debug info.

**Comment by Brummolix** [comment]
This seem to be a bug in Thunderbird, as an Addon should not be able to crash Thunderbird (it only runs JavaScript).
Of course, the AddOn might trigger something that Thunderbird does not expec...
Does it also happen if you archive multiple mails with normal Thunderbird functions (mark multiple ones and press archive in the context menu)?

Probably it would be good to open a Thunderbird bug under https://bugzilla.mozilla.org/enter_bug.cgi?product=Thunderbird

**Comment by Nono-m0le** [comment]
tracked here: https://bugzilla.mozilla.org/show_bug.cgi?id=1794561

**Comment by Nono-m0le** [comment]
Cannot reproduce
