### ISSUE TITLE
Reversing folder creation

### ISSUE THREAD

**Issue by pedjas** [Brummolix/AutoarchiveReloaded#83]
Is it possible to get option to reverse organization of folders in Archive?

Now, in Archive folder for each year is created and than within that folder, folders are created and messages copied to them.

I find it odd. I have quite elaborate subfolder structure where messages are stored by number of filtering rules. After I archived them, I ended up with same message folder scattered on number of years.

When I am looking for some archived message and I do not know exact date or info that would help me using search, I have to open each year, and then subfolders to find it.

For me, it would be more appropriate that, when messages from folder are archived, that folder is created in Archive and then for each year, subfolders should be created within that folder. That way, all messages archived from one folder would be also at the designated folder in Archive, just separated by year - much easier to use. I believe this would be helpful for everyone who do have messages sorted out by subfolders.

**Comment by Brummolix** [comment]
The Addon uses the features from Thunderbird to archive the messages.
Therefore only the folder options available in Thunderbird itself are possible.
You might request it at https://bugzilla.mozilla.org/enter_bug.cgi?product=Thunderbird
