### ISSUE TITLE
`0 messages found to archive`: TB 115.1.1, Garuda Linux

### ISSUE THREAD

**Issue by Lippiece** [Brummolix/AutoarchiveReloaded#87]
Thanks for the extension.

This is what happens on manual archive. 

`search done for 'Inbox' in account '<my account>' -> 0 messages found to archive`

<details>

<summary>Add-on settings</summary>

![image](https://github.com/Brummolix/AutoarchiveReloaded/assets/47634624/b22ed0e6-6f63-42b8-8ac7-8843a11b1331)

</details>

<details>

<summary>Account settings</summary>

![image](https://github.com/Brummolix/AutoarchiveReloaded/assets/47634624/758a5e37-660b-4b3d-9569-83efd19eca2f)

</details>

**Comment by Brummolix** [comment]
Strange.

It does not found any message according to the settings of the account. Either there are no messages at all or none of them fits to the settings (first screenshot).
The Thunderbird account settings does not matter at this stage.

Are you sure, you have the settings in the right account (every account has its own settings)?

Unfortunately no more details will be logged for this process at the moment, therefore without knowing the concrete messages it is hard to tell what's going on...

**Comment by Lippiece** [comment]
I've found out that this is because every message is my inbox is automatically tagged, but settings for this scenario are unset. I assumed if I left the option unchecked, the extension would just ignore tags.

Thanks for looking into this and again for the extension.
