### ISSUE TITLE
Tbird 68.12.1 (64bit) and Auto archive reloaded 1.0.0.6, archived forlders get created on the imap server instead of local archives on the PC.

### ISSUE THREAD

**Issue by ecomstation** [Brummolix/AutoarchiveReloaded#88]
Hi,

i'm using tbird 68.12.1 since i've some old extensions that don't work with newer builds and i also prefere this version 68 UI.

It happens that AutoArchiveReloaded move old emails into "archive" folders created in the IMAP tree on the mail server, instead of
moving them on local folders on the PC.

e.g.  imap://massimo3%40mydomain.it@192.168.1.x/Archives/2023
(the imap daemon is on my LAN, so you see 192.168.1..)

any help?
thanks

massimo

**Comment by Brummolix** [comment]
The addon does not have a setting for the target folder.
Instead you have to setup the normale archive settings in Thunderbird.
Normally it should be a setting for every account (right click at an account, choose "Properties", choose "Copies and folders" and find the archive settings there)

**Comment by ecomstation** [comment]
Sorry, no, thunderbird only have settings to keep a local "cache" of messages for imap.
So how can i tell thunderbird that archives folder must be local and not on the imap server.

thanks

**Comment by Brummolix** [comment]
> Sorry, no, thunderbird

I don't understand. You want to use a thunderbird addon without thunderbird?

In Thunderbird right click at an account, choose "Properties". There choose "Copies and folders". There you should find settings for message archives. Choose other folder and setup your own folder.
Should look similar to this  image
! ( https://assets-prod.sumo.prod.webservices.mozgcp.net/media/uploads/gallery/images/2018-01-30-19-51-55-686843.png )

**Comment by ecomstation** [comment]
now i understand the right settings and it work
thank you

massimo
