### ISSUE TITLE
[0.9.8] Does not find (all) message to archive

### ISSUE THREAD

**Issue by RalfWW** [Brummolix/AutoarchiveReloaded#9]
Have defined 
"Archiviere alle anderen Nachrichten älter als 364 Tage"
as the only setting.

Error-Log shows checking of the folders but no message was detected.
But there a lot of message older than 364 days...

Ralf

**Comment by Brummolix** [comment]
Are the messages unread, marked with a star or tagged?

**Comment by RalfWW** [comment]
unread!

I see: NO unread, "stared" or tagged message will be archive until it is
checked in the settings. Right?

Did I oversee that somewhere in the description?

Thanks

Ralf


Am 14.04.2015 um 19:15 schrieb Brummolix:

**Comment by Brummolix** [comment]
Right.
